name: Build LOVE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build LOVE
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 拉取完整历史以支持标签检出

      - name: Checkout to Tag 11.5
        run: git checkout 11.5

      - name: Clone LOVE Library at Tag 11.5
        run: |
          git clone https://github.com/love2d/love libs/love
          cd libs/love
          git checkout 11.5

      - name: Configure with CMake
        run: |
          cmake -G "Visual Studio 17 2022" -A x64 -S . -B build

      - name: Build LOVE
        run: cmake --build build --target love/love --config Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: love-build
          path: megasource/build
