name: build-neko

on:
  workflow_dispatch:

defaults:
  run:
    shell: cmd

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3   
    
    - name: Install Qt 6.7.3
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        set-env: 'true'
        add-tools-to-path: 'true'
 
    - name: build nekoray C++
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        choco install busybox
        git clone https://github.com/MatsuriDayo/nekoray.git --recursive
        cd nekoray
        busybox sh ./libs/build_deps_all.sh
        mkdir build
        cd build
        cmake -GNinja -DQT_VERSION_MAJOR=6 -DCMAKE_BUILD_TYPE=Release ..
        ninja
        mkdir deploy
        copy nekobox.exe deploy
        windeployqt deploy\nekobox.exe
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: nekobox
        path: '${{ github.workspace }}/nekoray/build/deploy/'

