name: build-neko

on:
  workflow_dispatch:

defaults:
  run:
    shell: cmd.exe /k "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -startdir=none -arch=x64 -host_arch=x64

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3   
    
    - name: Install Qt 6.7.3
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/Qt'
        set-env: 'true'
        add-tools-to-path: 'true'
 
    - name: build nekoray C++
      run: |
        cl /?
        choco install busybox
        git clone https://github.com/MatsuriDayo/nekoray.git --recursive
        cd nekoray
        busybox sh ./libs/build_deps_all.sh
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{ github.workspace }}/Qt/Qt/6.7.3/msvc2019_64" ..
        ninja