name: build-alist

on:
  workflow_dispatch:
    inputs:
        ui-ver:
          description: "alist-web version tu build"
          required: true
        core-ver:
          description: "alist version tu build"
          required: true

jobs:
  build:
    name: Build AList
    runs-on: windows-latest

    defaults:
        run:
          shell: pwsh
      
    steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Build Alist
          run: |
            choco install busybox
            npm install -g pnpm 
            busybox ash script\alist.sh ${{ github.event.inputs.ui-ver }} ${{ github.event.inputs.core-ver }}
        

        - name: Upload build artifacts
          uses: actions/upload-artifact@v3
          with: 
            name: nekobox
            path: '${{ github.workspace }}/alist/alist.exe'